---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lit
spec:
  replicas: 1
  template:
    metadata:
      name: lit
      labels:
        base: lit
    spec:
      containers:
      - name: lit
        image: asia.gcr.io/nonononono/lit:latest
        imagePullPolicy: Always
        command: ["sh", "-c", "tail -f /dev/null"]
        env:
        - name: RAILS_ENV
          value: production
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: litdb
              key: password

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=list-213015:asia-northeast1-c:litserver=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: gcread
