---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lit
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lit-lb
    # kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: lit-tls
  backend:
    serviceName: lit
    servicePort: 80
