---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: lit
spec:
  template:
    spec:
      # imagePullSecrets:
      # - name: ap-northeast-2-ecr-registry
      containers:
      - name: lit
        image: lit:latest
